<?php
/**********************************
 * head.inc
 * @author megan
 **********************************
*/
function head()
{
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Admin</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
<!--    <link href="/css/animate.min.css" rel="stylesheet"> -->
    <link href="/css/animate.css" rel="stylesheet" />
    <link href="/css/prettyPhoto.css" rel="stylesheet"> 
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/dixie.css" rel="stylesheet">
    <script src="/js/jquery.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/jquery.prettyPhoto.js"></script>
    <script src="/js/jquery.isotope.min.js"></script>
    <script src="/js/wow.min.js"></script>
    <script src="/js/main.js"></script>

  </head>
  <body>
<?php
}
?>
