<?php

/***********************************
 * about.inc 
 * @author  megan
 ***********************************
*/			
function about()  
{
?>
    <section id="about">
      <p><br><br><br><br></p>
      <div class="container">
        <div class="center">
          <div class="col-md-6 col-md-offset-3">
            <h2>Megan Williams</h2>
            <hr>
            <div id="aboutthatdixie"></div>
          </div>
        </div>
      </div>
    </section>
<?php
}
?>
