<?php

/*********************************
 * fun.inc
 * @author megan
 *********************************
*/
function fun()
{
?>
    <section id="funshit">
      <p><br><br><br><br></p>
      <div class="container">
        <div class="center">
          <div class="col-md-6 col-md-offset-3">
            <h2>Fun</h2>
            <hr>    
            <div id="fun"></div>
          </div>
        </div>
      </div>
      <p><br><br></p>
    </section>
<?php
}
?>