<?php

/*********************************
 * fun.inc
 * @author megan
 *********************************
*/
function fun()
{
?>
    <section id="features">
      <div class="container">
        <div class="row">
          <div class="center">
            <div class="col-md-6 col-md-offset-3">
              <h2>Fun</h2>
              <hr>    
              <p class="lead">Comming Soon:</p>
            </div>
          </div>
        </div>
      </div>
    </section>
<?php
}
?>