<?php

/*********************************
 * projects.inc
 * @author megan
 *********************************
*/
function projects()
{
?>
    <section id="portfolio">
      <div class="container">
        <div class="center">
          <div class="col-md-6 col-md-offset-3">
            <h2>Programming Projects</h2>
            <hr>
            <p class="lead"><a href="/admin/">Login to admin site</a></p>
          </div>
        </div>
      </div>
    </section>
<?php
}
?>