<?php

/*********************************
 * projects.inc
 * @author megan
 *********************************
*/
function projects()
{
?>
    <section id="projectshit">
      <p><br><br><br><br></p>
      <div class="container">
        <div class="center">
          <div class="col-md-6 col-md-offset-3">
            <h2>Programming Projects</h2>
            <hr>
            <div id="projects"></div>
          </div>
        </div>
      </div>
    </section>
<?php
}
?>